---
collections:
  - name: ansible.netcommon
    source: https://galaxy.ansible.com
  - name: ansible.posix
    source: https://galaxy.ansible.com
  - name: ansible.utils
    source: https://galaxy.ansible.com
  - name: ansible.windows
    source: https://galaxy.ansible.com
  - name: community.windows
    source: https://galaxy.ansible.com
