---
collections:
  - name: ansible.windows
    source: https://galaxy.ansible.com
    version: ">=1.5.0"  # win_powershell
  - name: community.general
    source: https://galaxy.ansible.com
  - name: community.windows
    source: https://galaxy.ansible.com
