---
# tasks file for sshockley.snmp

- name: 'Windows : Install SNMP Client'
  become_method: ansible.builtin.runas
  become_user: System
  become: true
  ansible.windows.win_powershell:
    parameters:
      Name: 'SNMP.Client~~~~0.0.1.0'
    script: |
      [CmdletBinding(SupportsShouldProcess)]
      param ([String]$Name)

      $Ansible.Changed = $false
      $capability = Get-WindowsCapability -Online -Name $Name
      if ($capability.State -ne 'Installed') {
          if ($PSCmdlet.ShouldProcess($Name, 'Add-WindowsCapability')) {
              Add-WindowsCapability -Online -Name $Name | Out-Null
          }
          $Ansible.Changed = $true
      }

- name: 'Windows : setting SNMP'
  ansible.windows.win_regedit:
    path: 'HKLM:\SYSTEM\CurrentControlSet\Services\SNMP\Parameters\{{ item.path }}'
    name: '{{ item.name }}'
    type: '{{ item.type }}'
    data: '{{ item.data }}'
  loop:
    - path: RFC1156Agent
      name: sysContact
      type: string
      data: '{{ snmp_contact | default() }}'
    - path: RFC1156Agent
      name: sysLocation
      type: string
      data: '{{ snmp_location | default() }}'
  notify:
    - Restart win snmp

- name: 'Windows : configure SNMP community'
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/windows_valid_communities.yml"

- name: 'Windows : configure permitted SNMP managers'
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/windows_permitted_managers.yml"

# - name: 'Windows : firewall rule to allow ICMP'
#   community.windows.win_firewall_rule:
#     name: ICMP
#     action: allow
#     direction: in
#     protocol: ICMPv4
#     remoteip: '{{ snmp_permitted_managers | join(',') }}'
#     state: present
#     enabled: true

# - name: 'Windows : firewall rule to allow SNMP-Service'
#   community.windows.win_firewall_rule:
#     name: SNMP
#     action: allow
#     direction: in
#     protocol: UDP
#     localport: '161'
#     remoteip: '{{ snmp_permitted_managers | join(',') }}'
#     state: present
#     enabled: true
