---
# tasks file for sbaerlocher.snmp

- name: 'Windows : install SNMP'
  ansible.windows.win_feature:
    name: "{{ snmp_name }}"
    state: present

- name: 'Windows : setting SNMP'
  ansible.windows.win_regedit:
    path: 'HKLM:\SYSTEM\CurrentControlSet\Services\SNMP\Parameters\{{ item.path }}'
    name: '{{ item.name }}'
    type: '{{ item.type }}'
    data: '{{ item.data }}'
  loop:
    - path: RFC1156Agent
      name: sysContact
      type: string
      data: '{{ snmp_contact | default() }}'
    - path: RFC1156Agent
      name: sysLocation
      type: string
      data: '{{ snmp_location | default() }}'
    - path: ValidCommunities
      name: '{{ snmp_community | default() }}'
      type: dword
      data: '4'
  notify:
    - Restart win snmp

- name: 'Windows : configure permitted SNMP managers'
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/windows_permitted_managers.yml"

- name: Enable all the Firewall rules in application group
  community.windows.win_firewall_rule:
    group: "@firewallapi.dll,-50303"
    enabled: true

# - name: 'Windows : firewall rule to allow ICMP'
#   community.windows.win_firewall_rule:
#     name: ICMP
#     action: allow
#     direction: in
#     protocol: ICMPv4
#     remoteip: '{{ snmp_permitted_managers | join(',') }}'
#     state: present
#     enabled: true

# - name: 'Windows : firewall rule to allow SNMP-Service'
#   community.windows.win_firewall_rule:
#     name: SNMP
#     action: allow
#     direction: in
#     protocol: UDP
#     localport: '161'
#     remoteip: '{{ snmp_permitted_managers | join(',') }}'
#     state: present
#     enabled: true
