---
name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: '3.14'
      - name: Install ansible-lint
        run: pip install ansible-core==2.21.5 ansible-lint==26.9.0
      - name: Install collection dependencies
        run: ansible-galaxy collection install -r requirements.yaml
      - name: Run ansible-lint
        run: ansible-lint
